### ISSUE TITLE
Resource里面的PostgreSQL示例数据库dvdrental.md和Load PostgreSQL Sample Database.pdf显示问题

### ISSUE THREAD

**Issue by cf3i** [njnucsta2022/DB2022FALL#2]
图片没渲染
PostgreSQL示例数据库dvdrental.md中[下载DVD租赁样本数据库](https://sp.postgresqltutorial.com/wp-content/uploads/2019/05/dvdrental.zip)无法访问

**Comment by komaba461** [comment]
试试这个[下载DVD租赁样本数据库](https://postgresqltutorial.com/wp-content/uploads/2019/05/dvdrental.zip)，[下载可打印的ER图](https://postgresqltutorial.com/wp-content/uploads/2018/03/printable-postgresql-sample-database-diagram.pdf)
